name: Build with CodeArtifact

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CODEARTIFACT_AUTH_TOKEN: 'CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID}} --region ${{ secrets.AWS_REGION }} --query authorizationToken --output text'
          CODEARTIFACT_DOMAIN_REPO: '${{ secrets.CODEARTIFACT_DOMAIN}}/${{ secrets.CODEARTIFACT_REPO}}'
          CODEARTIFACT_URL: 'https://${{ secrets.CODEARTIFACT_DOMAIN }}-${{  secrets.AWS_ACCOUNT_ID}}.d.codeartifact.${{ secrets.AWS_REGION}}.amazonaws.com/${{ secrets.CODEARTIFACT_DOMAIN }}/${{ secrets.CODEARTIFACT_REPO }}/' # Replace with actual URL
        run: echo "Environment variables set."
         echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --region ${{ secrets.AWS_REGION }} --query authorizationToken --output text)" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean build -s .m2/settings.xml -X
